import { writeFileSync } from 'fs'
import { join } from 'path'
import { buildFolderTree } from '../analyzer/structureAnalyzer.js'

/**
 * Generates agent_<folderName>_instructions.md inside the given folder.
 * @param {Object} folderInfo - Folder metadata
 * @param {Object} patternInfo - Pattern detection result
 * @param {Object} languageInfo - Language detection result
 * @param {Object} projectMeta - Project-level metadata
 */
export function generateInstructions(folderInfo, patternInfo, languageInfo, projectMeta) {
  const content = buildMarkdown(folderInfo, patternInfo, languageInfo, projectMeta)
  const fileName = `agent_${folderInfo.name.toLowerCase()}_instructions.md`
  const outputPath = join(folderInfo.path, fileName)
  writeFileSync(outputPath, content, 'utf8')
  return outputPath
}

function buildMarkdown(folderInfo, patternInfo, languageInfo, projectMeta) {
  const { name, relativePath, codeFiles, subdirNames, depth } = folderInfo
  const { role, description, agentHint, fileAnalysis, hasInterfaces, hasImplementations } = patternInfo
  const { lang, framework } = languageInfo
  const date = new Date().toISOString().split('T')[0]

  const sections = []

  // Header
  sections.push(`# ${name}/ — Agent Instructions`)
  sections.push(`> Generated by [skill-me-up](https://github.com/skill-me-up/skill-me-up) on ${date}`)
  sections.push(`> Project: **${projectMeta.name}** | Language: **${lang}** | Framework: **${framework}**`)
  sections.push('')

  // Overview
  sections.push('## Overview')
  sections.push(`**Path:** \`${relativePath}/\``)
  sections.push(`**Role:** ${role}`)
  sections.push('')
  sections.push(description)
  sections.push('')

  // Directory tree
  const tree = buildFolderTree(folderInfo.path, relativePath)
  if (tree) {
    sections.push('## Structure')
    sections.push('```')
    sections.push(tree)
    sections.push('```')
    sections.push('')
  }

  // Files breakdown
  sections.push('## Files')
  sections.push(buildFilesSection(fileAnalysis, codeFiles))

  // Interface / Implementation note
  if (hasInterfaces || hasImplementations) {
    sections.push('## Architecture Note')
    if (hasInterfaces && hasImplementations) {
      sections.push(
        'This folder contains both **interfaces** (contracts) and **implementations** (concrete classes). ' +
        'When modifying behavior, update the interface first if the contract changes, then the implementation.'
      )
    } else if (hasInterfaces) {
      sections.push(
        'This folder defines **interfaces / contracts**. ' +
        'Implementations live in a sibling folder (typically named `impl/` or `*Impl`).'
      )
    } else if (hasImplementations) {
      sections.push(
        'This folder contains **concrete implementations**. ' +
        'The corresponding interfaces/contracts are defined in a sibling folder.'
      )
    }
    sections.push('')
  }

  // Subdirectories
  if (subdirNames.length > 0) {
    sections.push('## Subdirectories')
    for (const sub of subdirNames) {
      sections.push(`- \`${sub}/\` — see \`agent_${sub.toLowerCase()}_instructions.md\` inside this folder`)
    }
    sections.push('')
  }

  // Agent instructions
  sections.push('## Instructions for AI Agents')
  sections.push(agentHint)
  sections.push('')

  // Relationships (if not top-level)
  if (depth > 1) {
    sections.push('## Context')
    sections.push(`This folder is nested inside \`${relativePath.split('/').slice(0, -1).join('/')}/\`. ` +
      `Check the parent folder's \`agent_${folderInfo.name.toLowerCase()}_instructions.md\` for broader context.`)
    sections.push('')
  }

  // Footer
  sections.push('---')
  sections.push('*This file was auto-generated by skill-me-up. Do not edit manually — re-run the tool to refresh.*')

  return sections.join('\n')
}

function buildFilesSection(fileAnalysis, allCodeFiles) {
  const lines = []
  const { interfaces, implementations, controllers, tests, models, configs, utils, other } = fileAnalysis

  const groups = [
    { label: 'Interfaces / Contracts', items: interfaces },
    { label: 'Implementations', items: implementations },
    { label: 'Controllers / Handlers', items: controllers },
    { label: 'Models / Entities / DTOs', items: models },
    { label: 'Configuration', items: configs },
    { label: 'Utilities / Helpers', items: utils },
    { label: 'Tests', items: tests },
    { label: 'Other', items: other },
  ]

  for (const group of groups) {
    if (group.items.length === 0) continue
    lines.push(`### ${group.label}`)
    for (const item of group.items) {
      lines.push(`- \`${item.file}\` — ${item.note}`)
    }
    lines.push('')
  }

  if (allCodeFiles.length === 0) {
    lines.push('*No code files detected in this folder.*')
    lines.push('')
  }

  return lines.join('\n')
}
