import { writeFileSync } from 'fs'
import { join } from 'path'
import { buildFolderTree } from '../analyzer/structureAnalyzer.js'

/**
 * Generates agent_<folderName>_instructions.md inside the given folder.
 * Uses writeFileSync which overwrites by default -- safe to re-run.
 * @param {Object} folderInfo - Folder metadata
 * @param {Object} patternInfo - Pattern detection result (includes deepAnalysis, detectedPatterns, dependencies, howToAdd)
 * @param {Object} languageInfo - Language detection result
 * @param {Object} projectMeta - Project-level metadata
 */
export function generateInstructions(folderInfo, patternInfo, languageInfo, projectMeta) {
  const content = buildMarkdown(folderInfo, patternInfo, languageInfo, projectMeta)
  const fileName = `agent_${folderInfo.name.toLowerCase()}_instructions.md`
  const outputPath = join(folderInfo.path, fileName)
  // writeFileSync overwrites existing files by default -- no duplicate files on re-run
  writeFileSync(outputPath, content, 'utf8')
  return outputPath
}

function buildMarkdown(folderInfo, patternInfo, languageInfo, projectMeta) {
  const { name, relativePath, codeFiles, subdirNames, depth } = folderInfo
  const {
    role, description, agentHint, fileAnalysis,
    hasInterfaces, hasImplementations,
    deepAnalysis, detectedPatterns, dependencies, howToAdd,
  } = patternInfo
  const { lang, framework } = languageInfo
  const date = new Date().toISOString().split('T')[0]

  const sections = []

  // ─── Header ──────────────────────────────────────────────────────────────
  sections.push(`# ${name}/ — Agent Instructions`)
  sections.push(`> Generated by [skill-me-up](https://github.com/skill-me-up/skill-me-up) on ${date}`)
  sections.push(`> Project: **${projectMeta.name}** | Language: **${lang}** | Framework: **${framework}**`)
  sections.push('')

  // ─── Overview ────────────────────────────────────────────────────────────
  sections.push('## Overview')
  sections.push(`**Path:** \`${relativePath}/\``)
  sections.push(`**Role:** ${role}`)
  sections.push(`**Files:** ${codeFiles.length} code file(s)`)
  sections.push('')
  sections.push(description)
  sections.push('')

  // ─── Project Conventions ─────────────────────────────────────────────────
  if (patternInfo.conventions) {
    const conventionsContent = buildConventionsSection(patternInfo.conventions)
    if (conventionsContent) {
      sections.push('## Project Conventions')
      sections.push(conventionsContent)
      sections.push('')
    }
  }

  // ─── Directory tree ──────────────────────────────────────────────────────
  const tree = buildFolderTree(folderInfo.path, relativePath)
  if (tree) {
    sections.push('## Structure')
    sections.push('```')
    sections.push(tree)
    sections.push('```')
    sections.push('')
  }

  // ─── Classes & Interfaces (DEEP ANALYSIS) ────────────────────────────────
  if (deepAnalysis && deepAnalysis.length > 0) {
    const classSection = buildClassesSection(deepAnalysis)
    if (classSection) {
      sections.push('## Classes & Interfaces')
      sections.push('')
      sections.push(classSection)
      sections.push('')
    }
  }

  // ─── Key Patterns (DETECTED PATTERNS) ────────────────────────────────────
  if (detectedPatterns && detectedPatterns.length > 0) {
    sections.push('## Key Patterns')
    sections.push('')
    for (const pattern of detectedPatterns) {
      sections.push(`### ${pattern.label}`)
      sections.push(pattern.description)
      sections.push('')
    }
  }

  // ─── Files breakdown (original categorized view) ─────────────────────────
  sections.push('## Files by Category')
  sections.push(buildFilesSection(fileAnalysis, codeFiles))

  // ─── Interface / Implementation note ─────────────────────────────────────
  if (hasInterfaces || hasImplementations) {
    sections.push('## Architecture Note')
    if (hasInterfaces && hasImplementations) {
      sections.push(
        'This folder contains both **interfaces** (contracts) and **implementations** (concrete classes). ' +
        'When modifying behavior, update the interface first if the contract changes, then the implementation.'
      )
    } else if (hasInterfaces) {
      sections.push(
        'This folder defines **interfaces / contracts**. ' +
        'Implementations live in a sibling folder (typically named `impl/` or `*Impl`).'
      )
    } else if (hasImplementations) {
      sections.push(
        'This folder contains **concrete implementations**. ' +
        'The corresponding interfaces/contracts are defined in a sibling folder.'
      )
    }
    sections.push('')
  }

  // ─── How to add new code here (CONTEXTUAL INSTRUCTIONS) ──────────────────
  if (howToAdd && howToAdd.length > 0) {
    sections.push('## How to Add New Code Here')
    sections.push('')
    for (const instruction of howToAdd) {
      sections.push(`### ${instruction.title}`)
      sections.push('')
      for (let i = 0; i < instruction.steps.length; i++) {
        sections.push(`${i + 1}. ${instruction.steps[i]}`)
      }
      sections.push('')
    }
  }

  // ─── Dependencies (CROSS-FOLDER IMPORTS) ─────────────────────────────────
  if (dependencies && dependencies.length > 0) {
    sections.push('## Dependencies')
    sections.push('')
    sections.push('This folder imports from / depends on the following packages or folders:')
    sections.push('')
    for (const dep of dependencies) {
      sections.push(`- \`${dep}\``)
    }
    sections.push('')
  }

  // ─── Subdirectories ──────────────────────────────────────────────────────
  if (subdirNames.length > 0) {
    sections.push('## Subdirectories')
    for (const sub of subdirNames) {
      sections.push(`- \`${sub}/\` — see \`agent_${sub.toLowerCase()}_instructions.md\` inside this folder`)
    }
    sections.push('')
  }

  // ─── Agent instructions ──────────────────────────────────────────────────
  sections.push('## Instructions for AI Agents')
  sections.push(agentHint)
  sections.push('')

  // ─── Relationships (if not top-level) ────────────────────────────────────
  if (depth > 1) {
    sections.push('## Context')
    sections.push(`This folder is nested inside \`${relativePath.split('/').slice(0, -1).join('/')}/\`. ` +
      `Check the parent folder's instructions file for broader context.`)
    sections.push('')
  }

  // ─── Footer ──────────────────────────────────────────────────────────────
  sections.push('---')
  sections.push('*This file was auto-generated by skill-me-up. Re-run the tool to refresh (files are overwritten, not duplicated).*')

  return sections.join('\n')
}

// ─── Deep Classes & Interfaces Section ───────────────────────────────────────

function buildClassesSection(deepAnalysis) {
  const lines = []

  for (const fa of deepAnalysis) {
    if (fa.error) {
      lines.push(`### \`${fa.file}\``)
      lines.push(`*Could not read file: ${fa.error}*`)
      lines.push('')
      continue
    }

    const typeLabel = fa.classType ? fa.classType.charAt(0).toUpperCase() + fa.classType.slice(1) : 'File'
    lines.push(`### \`${fa.file}\` — ${typeLabel}: **${fa.className}**`)
    lines.push('')

    // Package / namespace
    if (fa.packageName) {
      lines.push(`- **Package:** \`${fa.packageName}\``)
    }

    // Extends / implements
    if (fa.extendsClass) {
      lines.push(`- **Extends:** \`${fa.extendsClass}\``)
    }
    if (fa.implementsInterfaces && fa.implementsInterfaces.length > 0) {
      lines.push(`- **Implements:** ${fa.implementsInterfaces.map(i => `\`${i}\``).join(', ')}`)
    }

    // Annotations at class level
    if (fa.classAnnotations && fa.classAnnotations.length > 0) {
      lines.push(`- **Annotations:** ${fa.classAnnotations.map(a => `\`@${a}\``).join(', ')}`)
    }

    // Field annotations (JPA entities)
    if (fa.fieldAnnotations && fa.fieldAnnotations.length > 0) {
      lines.push(`- **Field Annotations:** ${fa.fieldAnnotations.map(a => `\`@${a}\``).join(', ')}`)
    }

    // Public methods
    if (fa.methods && fa.methods.length > 0) {
      lines.push('')
      lines.push('**Public Methods:**')
      lines.push('')
      lines.push('| Method | Parameters | Returns | Annotation |')
      lines.push('|--------|-----------|---------|------------|')
      for (const method of fa.methods) {
        const params = method.params || '—'
        const ret = method.returnType || '—'
        const ann = method.annotation ? `\`${method.annotation}\`` : '—'
        lines.push(`| \`${method.name}\` | \`${truncate(params, 60)}\` | \`${ret}\` | ${ann} |`)
      }
      lines.push('')
    } else {
      lines.push('')
    }
  }

  return lines.length > 0 ? lines.join('\n') : null
}

// ─── Files by Category Section ───────────────────────────────────────────────

function buildFilesSection(fileAnalysis, allCodeFiles) {
  const lines = []
  const { interfaces, implementations, controllers, tests, models, configs, utils, other } = fileAnalysis

  const groups = [
    { label: 'Interfaces / Contracts', items: interfaces },
    { label: 'Implementations', items: implementations },
    { label: 'Controllers / Handlers', items: controllers },
    { label: 'Models / Entities / DTOs', items: models },
    { label: 'Configuration', items: configs },
    { label: 'Utilities / Helpers', items: utils },
    { label: 'Tests', items: tests },
    { label: 'Other', items: other },
  ]

  for (const group of groups) {
    if (group.items.length === 0) continue
    lines.push(`### ${group.label}`)
    for (const item of group.items) {
      lines.push(`- \`${item.file}\` — ${item.note}`)
    }
    lines.push('')
  }

  if (allCodeFiles.length === 0) {
    lines.push('*No code files detected in this folder.*')
    lines.push('')
  }

  return lines.join('\n')
}

// ─── Project Conventions Section ─────────────────────────────────────────────

/**
 * Renders the ## Project Conventions section from detected conventions data.
 * Returns null when conventions is null or empty — caller must check before pushing.
 * @param {Object|null} conventions - Conventions object from patternInfo.conventions
 * @returns {string|null} Rendered bullet list or null
 */
function buildConventionsSection(conventions) {
  if (!conventions || Object.keys(conventions).length === 0) return null

  const IMPORT_LABELS = {
    'relative-with-extension': 'relative paths with `.js` extension',
    'relative-bare': 'relative paths without extension',
    'absolute-bare': 'absolute/package paths',
  }

  const lines = []

  // Methods — may be plain object or Array (multi-language with differing styles)
  if (conventions.methods) {
    if (Array.isArray(conventions.methods)) {
      for (const entry of conventions.methods) {
        lines.push(`- **Methods (${entry.lang})**: ${entry.style} (e.g. \`${entry.example}\`)`)
      }
    } else {
      lines.push(`- **Methods**: ${conventions.methods.style} (e.g. \`${conventions.methods.example}\`)`)
    }
  }

  // Classes — may be plain object or Array (multi-language with differing styles)
  if (conventions.classes) {
    if (Array.isArray(conventions.classes)) {
      for (const entry of conventions.classes) {
        lines.push(`- **Classes (${entry.lang})**: ${entry.style} (e.g. \`${entry.example}\`)`)
      }
    } else {
      lines.push(`- **Classes**: ${conventions.classes.style} (e.g. \`${conventions.classes.example}\`)`)
    }
  }

  // Files — always a plain object (not language-split)
  if (conventions.files) {
    lines.push(`- **Files**: ${conventions.files.style} (e.g. \`${conventions.files.example}\`)`)
  }

  // Imports — always a plain object (style key → human-readable label)
  if (conventions.imports) {
    const label = IMPORT_LABELS[conventions.imports.style] || conventions.imports.style
    lines.push(`- **Imports**: ${label} (e.g. \`${conventions.imports.example}\`)`)
  }

  return lines.length > 0 ? lines.join('\n') : null
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function truncate(str, maxLen) {
  if (!str || str.length <= maxLen) return str
  return str.substring(0, maxLen - 3) + '...'
}

// ─── Test Exports ─────────────────────────────────────────────────────────────
export { buildConventionsSection }
