// Folder-level patterns: detected by folder name or file naming conventions
export const FOLDER_PATTERNS = [
  {
    id: 'controller',
    keywords: ['controller', 'controllers', 'ctrl', 'handler', 'handlers', 'routes', 'route', 'router'],
    role: 'HTTP / Presentation Layer',
    description: 'Handles incoming requests, delegates to the service layer, returns responses.',
    agentHint: 'To expose a new endpoint, add a file here. Never put business logic directly in controllers.',
  },
  {
    id: 'service',
    keywords: ['service', 'services', 'svc', 'usecase', 'usecases', 'use_case', 'use_cases', 'application'],
    role: 'Business Logic Layer',
    description: 'Contains the core application logic. Orchestrates calls between repositories/DAOs and other services.',
    agentHint: 'Business rules live here. Services call DAOs/repositories, never the other way around.',
  },
  {
    id: 'dao',
    keywords: ['dao', 'daos', 'repository', 'repositories', 'repo', 'repos', 'data', 'persistence', 'store'],
    role: 'Data Access Layer',
    description: 'Abstracts all database/storage operations. Interfaces here are implemented by concrete adapters.',
    agentHint: 'Add queries and storage logic here. Never put business logic in DAOs.',
  },
  {
    id: 'model',
    keywords: ['model', 'models', 'entity', 'entities', 'domain', 'dto', 'dtos', 'schema', 'schemas', 'types', 'interfaces'],
    role: 'Data Models / Domain',
    description: 'Defines the data structures, entities, DTOs and interfaces used across the application.',
    agentHint: 'When adding a new domain concept, define its type/entity here first.',
  },
  {
    id: 'middleware',
    keywords: ['middleware', 'middlewares', 'interceptor', 'interceptors', 'guard', 'guards', 'filter', 'filters'],
    role: 'Middleware / Cross-cutting Concerns',
    description: 'Auth, logging, validation, error handling — logic that runs across multiple requests.',
    agentHint: 'Place request-scoped cross-cutting logic here (auth checks, logging, rate limiting).',
  },
  {
    id: 'config',
    keywords: ['config', 'configuration', 'settings', 'environment', 'env', 'setup'],
    role: 'Configuration',
    description: 'Application configuration, environment variables, and initialization logic.',
    agentHint: 'All environment-dependent values should be read from here, never hardcoded elsewhere.',
  },
  {
    id: 'utils',
    keywords: ['utils', 'util', 'helpers', 'helper', 'shared', 'common', 'lib', 'libs', 'tools'],
    role: 'Utilities / Shared Helpers',
    description: 'Stateless, reusable helper functions shared across the codebase.',
    agentHint: 'Keep functions here pure and side-effect free. No business logic or DB calls.',
  },
  {
    id: 'components',
    keywords: ['components', 'component', 'ui', 'views', 'widgets'],
    role: 'UI Components',
    description: 'Reusable UI building blocks. Each component should be self-contained.',
    agentHint: 'Components should receive data via props and emit events. No direct store mutations inside components.',
  },
  {
    id: 'pages',
    keywords: ['pages', 'page', 'views', 'screens', 'screen'],
    role: 'Pages / Screens',
    description: 'Top-level views mapped to routes. Compose components and connect to state/services.',
    agentHint: 'Each file here typically maps to one route. Orchestrate components, do not implement logic here.',
  },
  {
    id: 'store',
    keywords: ['store', 'stores', 'state', 'redux', 'vuex', 'pinia', 'context'],
    role: 'State Management',
    description: 'Global application state. Manages shared data between components.',
    agentHint: 'Keep state normalized. Actions/mutations should be the only way to modify state.',
  },
  {
    id: 'composables',
    keywords: ['composables', 'composable', 'hooks', 'hook'],
    role: 'Composables / Hooks',
    description: 'Reusable stateful logic encapsulated for use across components.',
    agentHint: 'Extract repeated component logic into composables/hooks. Each should have a single responsibility.',
  },
  {
    id: 'test',
    keywords: ['test', 'tests', 'spec', 'specs', '__tests__', 'e2e', 'unit', 'integration'],
    role: 'Tests',
    description: 'Automated tests for the application.',
    agentHint: 'Mirror the src folder structure. Each module should have a corresponding test file.',
  },
  {
    id: 'api',
    keywords: ['api', 'apis', 'endpoints', 'graphql', 'rest', 'grpc'],
    role: 'API Definitions',
    description: 'API schemas, endpoint definitions, or client adapters.',
    agentHint: 'API contracts are defined here. Keep consistent naming and versioning.',
  },
]

// File-level pattern suffixes (for detecting interface vs implementation)
export const FILE_PATTERNS = [
  { suffix: 'Impl', role: 'Implementation', note: 'Concrete implementation of an interface' },
  { suffix: 'Interface', role: 'Interface', note: 'Abstract contract' },
  { suffix: 'Dao', role: 'DAO interface', note: 'Data access interface' },
  { suffix: 'DaoImpl', role: 'DAO implementation', note: 'Concrete data access implementation' },
  { suffix: 'Service', role: 'Service interface', note: 'Business logic interface' },
  { suffix: 'ServiceImpl', role: 'Service implementation', note: 'Concrete business logic implementation' },
  { suffix: 'Controller', role: 'Controller', note: 'HTTP request handler' },
  { suffix: 'Repository', role: 'Repository', note: 'Data repository' },
  { suffix: 'Entity', role: 'Entity', note: 'Domain entity / DB model' },
  { suffix: 'Dto', role: 'DTO', note: 'Data Transfer Object' },
  { suffix: 'DTO', role: 'DTO', note: 'Data Transfer Object' },
  { suffix: 'Model', role: 'Model', note: 'Data model' },
  { suffix: 'Test', role: 'Test', note: 'Test file' },
  { suffix: 'Spec', role: 'Test', note: 'Test specification' },
  { suffix: 'Guard', role: 'Guard', note: 'Route/auth guard' },
  { suffix: 'Middleware', role: 'Middleware', note: 'Middleware function' },
  { suffix: 'Resolver', role: 'Resolver', note: 'GraphQL resolver' },
]
